// קצובות לינה - מהדורה 23
const LODGING_DATA = [
{country:"Albania",code:"AL",region:"כל המדינה",amount:150,currency:"EUR"},
{country:"Angola",code:"AO",region:"כל המדינה",amount:325,currency:"USD"},
{country:"Antigua and Barbuda",code:"AG",region:"כל המדינה",amount:445,currency:"USD"},
{country:"Argentina",code:"AR",region:"כל המדינה",amount:240,currency:"USD"},
{country:"Armenia",code:"AM",region:"כל המדינה",amount:140,currency:"USD"},
{country:"Australia",code:"AU",region:"Sydney",amount:345,currency:"AUD"},
{country:"Australia",code:"AU",region:"יתר המדינה",amount:250,currency:"AUD"},
{country:"Austria",code:"AT",region:"כל המדינה",amount:180,currency:"EUR"},
{country:"Azerbaijan",code:"AZ",region:"כל המדינה",amount:145,currency:"USD"},
{country:"Bahamas",code:"BS",region:"כל המדינה",amount:415,currency:"USD"},
{country:"Bahrain",code:"BH",region:"כל המדינה",amount:165,currency:"USD"},
{country:"Barbados",code:"BB",region:"כל המדינה",amount:365,currency:"USD"},
{country:"Belarus",code:"BY",region:"כל המדינה",amount:130,currency:"USD"},
{country:"Belgium",code:"BE",region:"כל המדינה",amount:235,currency:"EUR"},
{country:"Belize",code:"BZ",region:"כל המדינה",amount:195,currency:"USD"},
{country:"Benin",code:"BJ",region:"כל המדינה",amount:175,currency:"USD"},
{country:"Bolivia",code:"BO",region:"כל המדינה",amount:125,currency:"USD"},
{country:"Bosnia",code:"BA",region:"כל המדינה",amount:110,currency:"USD"},
{country:"Botswana",code:"BW",region:"כל המדינה",amount:135,currency:"USD"},
{country:"Brazil",code:"BR",region:"יתר המדינה",amount:170,currency:"USD"},
{country:"Brazil",code:"BR",region:"Sao Paulo",amount:200,currency:"USD"},
{country:"Brunei",code:"BN",region:"כל המדינה",amount:145,currency:"USD"},
{country:"Bulgaria",code:"BG",region:"כל המדינה",amount:150,currency:"EUR"},
{country:"Burkina Faso",code:"BF",region:"כל המדינה",amount:160,currency:"USD"},
{country:"Burundi",code:"BI",region:"כל המדינה",amount:145,currency:"USD"},
{country:"Cambodia",code:"KH",region:"כל המדינה",amount:120,currency:"USD"},
{country:"Cameroon",code:"CM",region:"כל המדינה",amount:210,currency:"USD"},
{country:"Canada",code:"CA",region:"כל המדינה",amount:340,currency:"CAD"},
{country:"Central African Republic",code:"CF",region:"כל המדינה",amount:125,currency:"USD"},
{country:"Chad",code:"TD",region:"כל המדינה",amount:240,currency:"USD"},
{country:"Chile",code:"CL",region:"כל המדינה",amount:185,currency:"USD"},
{country:"China",code:"CN",region:"כל המדינה",amount:1065,currency:"CNY"},
{country:"Colombia",code:"CO",region:"כל המדינה",amount:185,currency:"USD"},
{country:"Congo",code:"CG",region:"כל המדינה",amount:250,currency:"USD"},
{country:"Cook Islands",code:"CK",region:"כל המדינה",amount:495,currency:"NZD"},
{country:"Costa Rica",code:"CR",region:"כל המדינה",amount:195,currency:"USD"},
{country:"Cote d'Ivoire",code:"CI",region:"כל המדינה",amount:185,currency:"EUR"},
{country:"Croatia",code:"HR",region:"כל המדינה",amount:120,currency:"EUR"},
{country:"Cuba",code:"CU",region:"כל המדינה",amount:160,currency:"USD"},
{country:"Cyprus",code:"CY",region:"כל המדינה",amount:165,currency:"EUR"},
{country:"Czech Republic",code:"CZ",region:"כל המדינה",amount:140,currency:"EUR"},
{country:"Democratic Republic of the Congo",code:"CD",region:"כל המדינה",amount:225,currency:"USD"},
{country:"Denmark",code:"DK",region:"כל המדינה",amount:1690,currency:"DKK"},
{country:"Djibouti",code:"DJ",region:"כל המדינה",amount:230,currency:"USD"},
{country:"Dominican Republic",code:"DO",region:"כל המדינה",amount:205,currency:"USD"},
{country:"East Timor",code:"TL",region:"כל המדינה",amount:140,currency:"USD"},
{country:"Ecuador",code:"EC",region:"כל המדינה",amount:220,currency:"USD"},
{country:"Egypt",code:"EG",region:"כל המדינה",amount:190,currency:"USD"},
{country:"El Salvador",code:"SV",region:"כל המדינה",amount:185,currency:"USD"},
{country:"Equatorial Guinea",code:"GQ",region:"כל המדינה",amount:195,currency:"USD"},
{country:"Eritrea",code:"ER",region:"כל המדינה",amount:165,currency:"USD"},
{country:"Estonia",code:"EE",region:"כל המדינה",amount:140,currency:"EUR"},
{country:"Ethiopia",code:"ET",region:"כל המדינה",amount:140,currency:"USD"},
{country:"Fiji",code:"FJ",region:"כל המדינה",amount:160,currency:"USD"},
{country:"Finland",code:"FI",region:"כל המדינה",amount:175,currency:"EUR"},
{country:"France",code:"FR",region:"Paris",amount:400,currency:"EUR"},
{country:"France",code:"FR",region:"יתר המדינה",amount:270,currency:"EUR"},
{country:"Gabon",code:"GA",region:"כל המדינה",amount:235,currency:"USD"},
{country:"Georgia",code:"GE",region:"כל המדינה",amount:175,currency:"USD"},
{country:"Germany",code:"DE",region:"יתר המדינה",amount:180,currency:"EUR"},
{country:"Germany",code:"DE",region:"Munich",amount:230,currency:"EUR"},
{country:"Ghana",code:"GH",region:"כל המדינה",amount:270,currency:"USD"},
{country:"Greece",code:"GR",region:"כל המדינה",amount:180,currency:"EUR"},
{country:"Guatemala",code:"GT",region:"כל המדינה",amount:160,currency:"USD"},
{country:"Guinea",code:"GN",region:"כל המדינה",amount:160,currency:"EUR"},
{country:"Guyana",code:"GY",region:"כל המדינה",amount:170,currency:"USD"},
{country:"Haiti",code:"HT",region:"כל המדינה",amount:185,currency:"USD"},
{country:"Honduras",code:"HN",region:"כל המדינה",amount:185,currency:"USD"},
{country:"Hong Kong",code:"HK",region:"כל המדינה",amount:1815,currency:"HKD"},
{country:"Hungary",code:"HU",region:"כל המדינה",amount:150,currency:"EUR"},
{country:"Iceland",code:"IS",region:"כל המדינה",amount:315,currency:"USD"},
{country:"India",code:"IN",region:"כל המדינה",amount:190,currency:"USD"},
{country:"Indonesia",code:"ID",region:"כל המדינה",amount:120,currency:"USD"},
{country:"Irish Republic",code:"IE",region:"כל המדינה",amount:180,currency:"EUR"},
{country:"Italy",code:"IT",region:"כל המדינה",amount:295,currency:"EUR"},
{country:"Jamaica",code:"JM",region:"כל המדינה",amount:280,currency:"USD"},
{country:"Japan",code:"JP",region:"Tokyo",amount:37120,currency:"JPY"},
{country:"Japan",code:"JP",region:"יתר המדינה",amount:21025,currency:"JPY"},
{country:"Jordan",code:"JO",region:"כל המדינה",amount:90,currency:"JOD"},
{country:"Kazakhstan",code:"KZ",region:"כל המדינה",amount:145,currency:"USD"},
{country:"Kenya",code:"KE",region:"כל המדינה",amount:210,currency:"USD"},
{country:"Korea Republic",code:"KR",region:"כל המדינה",amount:180,currency:"USD"},
{country:"Kosovo",code:"XK",region:"כל המדינה",amount:95,currency:"EUR"},
{country:"Kyrgyzstan",code:"KG",region:"כל המדינה",amount:130,currency:"USD"},
{country:"Laos",code:"LA",region:"כל המדינה",amount:120,currency:"USD"},
{country:"Latvia",code:"LV",region:"כל המדינה",amount:95,currency:"EUR"},
{country:"Lesotho",code:"LS",region:"כל המדינה",amount:110,currency:"USD"},
{country:"Liberia",code:"LR",region:"כל המדינה",amount:225,currency:"USD"},
{country:"Lithuania",code:"LT",region:"כל המדינה",amount:105,currency:"EUR"},
{country:"Luxembourg",code:"LU",region:"כל המדינה",amount:235,currency:"EUR"},
{country:"Macau",code:"MO",region:"כל המדינה",amount:190,currency:"USD"},
{country:"Macedonia",code:"MK",region:"כל המדינה",amount:95,currency:"EUR"},
{country:"Madagascar",code:"MG",region:"כל המדינה",amount:120,currency:"EUR"},
{country:"Malawi",code:"MW",region:"כל המדינה",amount:165,currency:"USD"},
{country:"Malaysia",code:"MY",region:"כל המדינה",amount:115,currency:"USD"},
{country:"Maldives",code:"MV",region:"כל המדינה",amount:300,currency:"USD"},
{country:"Mali",code:"ML",region:"כל המדינה",amount:175,currency:"USD"},
{country:"Malta",code:"MT",region:"כל המדינה",amount:220,currency:"EUR"},
{country:"Mauritania",code:"MR",region:"כל המדינה",amount:135,currency:"EUR"},
{country:"Mauritius",code:"MU",region:"כל המדינה",amount:315,currency:"USD"},
{country:"Mexico",code:"MX",region:"כל המדינה",amount:165,currency:"USD"},
{country:"Moldova",code:"MD",region:"כל המדינה",amount:150,currency:"EUR"},
{country:"Monaco",code:"MC",region:"כל המדינה",amount:325,currency:"EUR"},
{country:"Mongolia",code:"MN",region:"כל המדינה",amount:135,currency:"USD"},
{country:"Montenegro",code:"ME",region:"כל המדינה",amount:90,currency:"EUR"},
{country:"Morocco",code:"MA",region:"כל המדינה",amount:235,currency:"USD"},
{country:"Mozambique",code:"MZ",region:"כל המדינה",amount:170,currency:"USD"},
{country:"Myanmar",code:"MM",region:"כל המדינה",amount:100,currency:"USD"},
{country:"Namibia",code:"NA",region:"כל המדינה",amount:140,currency:"USD"},
{country:"Nepal",code:"NP",region:"כל המדינה",amount:180,currency:"USD"},
{country:"Netherlands",code:"NL",region:"Amsterdam",amount:320,currency:"EUR"},
{country:"Netherlands",code:"NL",region:"יתר המדינה",amount:190,currency:"EUR"},
{country:"New Zealand",code:"NZ",region:"Niue",amount:445,currency:"USD"},
{country:"New Zealand",code:"NZ",region:"יתר המדינה",amount:280,currency:"NZD"},
{country:"Nicaragua",code:"NI",region:"כל המדינה",amount:155,currency:"USD"},
{country:"Niger",code:"NE",region:"כל המדינה",amount:170,currency:"USD"},
{country:"Nigeria",code:"NG",region:"כל המדינה",amount:205,currency:"USD"},
{country:"Norway",code:"NO",region:"כל המדינה",amount:1815,currency:"NOK"},
{country:"Oman",code:"OM",region:"כל המדינה",amount:245,currency:"USD"},
{country:"Panama",code:"PA",region:"כל המדינה",amount:160,currency:"USD"},
{country:"Papua New Guinea",code:"PG",region:"כל המדינה",amount:175,currency:"USD"},
{country:"Paraguay",code:"PY",region:"כל המדינה",amount:120,currency:"USD"},
{country:"Peru",code:"PE",region:"כל המדינה",amount:170,currency:"USD"},
{country:"Philippines",code:"PH",region:"כל המדינה",amount:180,currency:"USD"},
{country:"Poland",code:"PL",region:"כל המדינה",amount:165,currency:"USD"},
{country:"Portugal",code:"PT",region:"כל המדינה",amount:165,currency:"EUR"},
{country:"Puerto Rico",code:"PR",region:"כל המדינה",amount:355,currency:"USD"},
{country:"Qatar",code:"QA",region:"כל המדינה",amount:155,currency:"USD"},
{country:"Romania",code:"RO",region:"כל המדינה",amount:130,currency:"EUR"},
{country:"Russia",code:"RU",region:"Moscow",amount:17500,currency:"RUB"},
{country:"Russia",code:"RU",region:"יתר המדינה",amount:15300,currency:"RUB"},
{country:"Rwanda",code:"RW",region:"כל המדינה",amount:155,currency:"USD"},
{country:"Samoa",code:"WS",region:"כל המדינה",amount:250,currency:"USD"},
{country:"Saudi Arabia",code:"SA",region:"כל המדינה",amount:735,currency:"SAR"},
{country:"Senegal",code:"SN",region:"כל המדינה",amount:220,currency:"USD"},
{country:"Serbia",code:"RS",region:"כל המדינה",amount:125,currency:"EUR"},
{country:"Seychelles",code:"SC",region:"כל המדינה",amount:250,currency:"EUR"},
{country:"Sierra Leone",code:"SL",region:"כל המדינה",amount:180,currency:"USD"},
{country:"Singapore",code:"SG",region:"כל המדינה",amount:410,currency:"SGD"},
{country:"Slovakia",code:"SK",region:"כל המדינה",amount:130,currency:"EUR"},
{country:"Slovenia",code:"SI",region:"כל המדינה",amount:135,currency:"EUR"},
{country:"Somaliland",code:"SO",region:"כל המדינה",amount:140,currency:"USD"},
{country:"South Africa",code:"ZA",region:"כל המדינה",amount:120,currency:"USD"},
{country:"Spain",code:"ES",region:"כל המדינה",amount:270,currency:"EUR"},
{country:"Sri Lanka",code:"LK",region:"כל המדינה",amount:180,currency:"USD"},
{country:"Sudan",code:"SD",region:"כל המדינה",amount:215,currency:"USD"},
{country:"Surinam",code:"SR",region:"כל המדינה",amount:160,currency:"USD"},
{country:"Sweden",code:"SE",region:"כל המדינה",amount:1935,currency:"SEK"},
{country:"Switzerland",code:"CH",region:"Geneva",amount:420,currency:"CHF"},
{country:"Switzerland",code:"CH",region:"Zurich",amount:320,currency:"CHF"},
{country:"Switzerland",code:"CH",region:"יתר המדינה",amount:220,currency:"CHF"},
{country:"Taiwan",code:"TW",region:"כל המדינה",amount:175,currency:"USD"},
{country:"Tajikistan",code:"TJ",region:"כל המדינה",amount:140,currency:"USD"},
{country:"Tanzania",code:"TZ",region:"כל המדינה",amount:165,currency:"USD"},
{country:"Thailand",code:"TH",region:"כל המדינה",amount:135,currency:"USD"},
{country:"Togo",code:"TG",region:"כל המדינה",amount:125,currency:"EUR"},
{country:"Tonga",code:"TO",region:"כל המדינה",amount:160,currency:"USD"},
{country:"Trinidad and Tobago",code:"TT",region:"כל המדינה",amount:230,currency:"USD"},
{country:"Tunisia",code:"TN",region:"כל המדינה",amount:115,currency:"EUR"},
{country:"Turkey",code:"TR",region:"כל המדינה",amount:150,currency:"EUR"},
{country:"Turkmenistan",code:"TM",region:"כל המדינה",amount:180,currency:"USD"},
{country:"Uganda",code:"UG",region:"כל המדינה",amount:215,currency:"USD"},
{country:"Ukraine",code:"UA",region:"כל המדינה",amount:135,currency:"USD"},
{country:"United Arab Emirates",code:"AE",region:"כל המדינה",amount:300,currency:"USD"},
{country:"United Kingdom",code:"GB",region:"Central London",amount:270,currency:"GBP"},
{country:"United Kingdom",code:"GB",region:"יתר המדינה",amount:145,currency:"GBP"},
{country:"United States of America",code:"US",region:"Atlanta GA",amount:255,currency:"USD"},
{country:"United States of America",code:"US",region:"Boston MA",amount:420,currency:"USD"},
{country:"United States of America",code:"US",region:"Chicago IL",amount:270,currency:"USD"},
{country:"United States of America",code:"US",region:"Houston TX",amount:275,currency:"USD"},
{country:"United States of America",code:"US",region:"Los Angeles CA",amount:330,currency:"USD"},
{country:"United States of America",code:"US",region:"Miami FL",amount:255,currency:"USD"},
{country:"United States of America",code:"US",region:"New York NY",amount:520,currency:"USD"},
{country:"United States of America",code:"US",region:"San Francisco CA",amount:295,currency:"USD"},
{country:"United States of America",code:"US",region:"Washington DC",amount:415,currency:"USD"},
{country:"United States of America",code:"US",region:"יתר המדינה",amount:255,currency:"USD"},
{country:"Uruguay",code:"UY",region:"כל המדינה",amount:180,currency:"USD"},
{country:"Uzbekistan",code:"UZ",region:"כל המדינה",amount:150,currency:"USD"},
{country:"Venezuela",code:"VE",region:"כל המדינה",amount:160,currency:"USD"},
{country:"Vietnam",code:"VN",region:"כל המדינה",amount:150,currency:"USD"},
{country:"Zambia",code:"ZM",region:"כל המדינה",amount:205,currency:"USD"},
{country:"Zimbabwe",code:"ZW",region:"Harare",amount:180,currency:"USD"}
];
